configfile: 'config.yaml'

RUN_NAMES = sorted(config['data'])
REFERNCE_TRANSCRIPTOME_SEQS = dict(config['reference_transcriptomes'])

rule all:
    input:
        'sequencing_summary.feather',
        expand('sequences/{name}.fa.gz', name=RUN_NAMES),
        expand('tables/controls-mapq-{name}.txt.gz', name=RUN_NAMES),
        expand('alignments/{name}-{refsample}.bam.bai', name=RUN_NAMES,
                refsample=sorted(REFERNCE_TRANSCRIPTOME_SEQS))

include: 'workflows/basecalling.py'
include: 'workflows/sequence_alignments.py'
include: 'workflows/training_data_preparation.py'

